version: "2"

services:
  mosmix-postgis:
    image: mdillon/postgis:10-alpine
    environment:
      - POSTGRES_USER=mosmix
      - POSTGRES_PASSWORD=some-secure-password-change-me-123
    cap_drop:
      - ALL
    user: postgres
    restart: always
  processor:
    image: quay.io/codeformuenster/mosmix-processor:v20180703-1
    cap_drop:
      - ALL
    command: -db postgresql://mosmix:some-secure-password-change-me-123@mosmix-postgis?sslmode=disable
  api:
    image: quay.io/codeformuenster/mosmix-api:v20180703-1
    cap_drop:
      - ALL
    ports:
      - "3000:3000"
    restart: always
